// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDce1lgKEX6kF5mGQ65jY-1kKQGhFnLhAI',
    appId: '1:278013796994:web:f6503681b7f01b22490a9b',
    messagingSenderId: '278013796994',
    projectId: 'outfit-matcher-29856',
    authDomain: 'outfit-matcher-29856.firebaseapp.com',
    storageBucket: 'outfit-matcher-29856.firebasestorage.app',
    measurementId: 'G-MS1ML1HE54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJMz0ZnKbDkbmKhlDxNPEdwf5s2ytfR1Y',
    appId: '1:278013796994:android:b2dd36bab390c617490a9b',
    messagingSenderId: '278013796994',
    projectId: 'outfit-matcher-29856',
    storageBucket: 'outfit-matcher-29856.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCURYEZZoC1jZohuFTTK_0kAMeY_9iVujA',
    appId: '1:278013796994:ios:cb5e1e33718ec0e9490a9b',
    messagingSenderId: '278013796994',
    projectId: 'outfit-matcher-29856',
    storageBucket: 'outfit-matcher-29856.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCURYEZZoC1jZohuFTTK_0kAMeY_9iVujA',
    appId: '1:278013796994:ios:cb5e1e33718ec0e9490a9b',
    messagingSenderId: '278013796994',
    projectId: 'outfit-matcher-29856',
    storageBucket: 'outfit-matcher-29856.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );
}
